### PR TITLE
Enhancement: FindCommand

### PR DESCRIPTION
**Pull request by melvintzw**
#16 
Add ability to narrow search by specifying which fields to search.
- Create new predicate classes.
- Update parser to accept specifiers and construct the correct FindCommand Object.
- Edit FindCommand.java to accept a Predicate<Person> rather than a specific predicate.

### CODE REVIEW

**Comment by zhangriqi** [comment]
Well done!

**Comment by jonleeyz** [comment]
Updating your branch with the base branch @melvintzw! Will review again after.

**Comment by jonleeyz** [comment]
Looks good, just need those new JUnit tests!

**Review by jonleeyz — APPROVED** [review]
Looks all good, nice job @melvintzw!

**Pull request merged**
