### PR TITLE
Add menu items and keyboard shortcuts

### PR DESCRIPTION
**Pull request by jonleeyz**
- [x] `F2` | **List** all Persons in the database
- [x] `Alt` + `Q` | **Exit**
- [x] `Ctrl` + `Z` | **Undo**
- [x] `Ctrl` + `Y` | **Redo**
- [x] `Alt` + `C` | **Clear** the database
- [x] `Alt` + `H` | Show command **history**
- [x] `Ctrl` + `F` | **Populate** `CommandBox` with `FindCommand` prefixes
- [x] `Alt` + `A` | **Populate** `CommandBox` with `AddCommand` prefixes
- [x] `Alt` + `D` | **Populate** `CommandBox` with `DeleteCommand` prefixes
- [x] `Alt` + `E` | **Populate** `CommandBox` with `EditCommand` prefixes
- [x] `Alt` + `L` | **Populate** `CommandBox` with `LocateCommand` prefixes
- [x] `Alt` + `S` | **Populate** `CommandBox` with `SelectCommand` prefixes

_Will keep updating this description as later commits are pushed._

### CODE REVIEW

**Review by melvintzw — DISMISSED** [review]
Nice work

**Comment by jonleeyz** [comment]
**Things to be done:**\

- [ ] Update underlying implementation of PopulateRequestEvent.
- [ ] Handle immediately executable keyboard shortcuts (`undo`, `redo`, `clear`, etc).
- [ ] Update usage messages.
- [ ] Handle exceptions if any.
- [ ] Modify and add tests.

**Review by zhangriqi — APPROVED** [review]
Looks great.

**Comment by melvintzw** [comment]
Well done.

**Pull request merged**
