### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by zhangriqi**
Update documentation for locate command

### CODE REVIEW

**Review by melvintzw — APPROVED** [review]

**Comment by melvintzw** [comment]
@zhangriqi could you re-submit this PR? the status checks seem to be bugging and doesn't recognise that the checks have passed :\

**Comment by zhangriqi** [comment]
@melvintzw Sorry, I don't get. What do you mean that the checks doesn't recognize because it  seems to have passed.

**Comment by melvintzw** [comment]
Yup the checks are passing! but github isn't recognising that they passed

**Comment by zhangriqi** [comment]
@melvintzw I think I know what's going on. Because the master branch wasn't building successfully on my laptop, so I had to delete the repo and re-forked it from our team repo and now GitHub thinks I want to merge from unknown repositories because I already deleted them.

**Comment by zhangriqi** [comment]
@melvintzw  And it's happening again, IntelliJ is giving me many errors saying packages don't exist.

**Comment by melvintzw** [comment]
@zhangriqi hi ruiqi, jonlee was facing the same problems as well. This is because there is a new dependency called 'natty', from com.joestelmach. You can try using this command in the Terminal "gradlew processResources" or you can try to refork the upstream repo and import the gradle project to update the dependencies!

**Comment by melvintzw** [comment]
@zhangriqi after resolving the problems with the packages, you can merge your changes in your local repo and resubmit a new PR for this issue!

**Comment by jonleeyz** [comment]
Succeeded by PR #86, which was merged successfully. PR closed.

**Pull request closed without merging**
